export { Avatar, type AvatarProps } from './Avatar';
export {
  AvatarPicker,
  defaultLoadAvatarGallery,
  type AvatarGalleryLoader,
  type AvatarGalleryRequest,
  type AvatarPickerDownloads,
  type AvatarPickerErrorContext,
  type AvatarPickerErrorOperation,
  type AvatarPickerPalette,
  type AvatarPickerProps,
  type AvatarPickerStyle,
} from './AvatarPicker';

// Explicitly mirror the public root API so React consumers need one install,
// while keeping future core additions deliberate and browser helpers separate.
export {
  RECIPE_VERSION,
  backgroundShapeNames,
  createAvatar,
  createRecipe,
  generateAvatar,
  generateGallery,
  generateParams,
  getBaseTypeCatalog,
  getDefaultParams,
  getPalette,
  getTheme,
  paletteNames,
  palettes,
  parseRecipe,
  themeNames,
  themes,
} from 'avatarka';
export type {
  AdventurersParams,
  AvatarOptions,
  AvatarRecipe,
  AvatarRenderInput,
  BackgroundShape,
  BaseTypeCatalog,
  BotsParams,
  CrittersParams,
  GalleryOptions,
  GeneratedAvatar,
  NooksParams,
  OddlingsParams,
  OrbsParams,
  Palette,
  PaletteColors,
  PaletteName,
  FolksParams,
  Seed,
  SnacksParams,
  ThemeMetadata,
  ThemeMetadataMap,
  ThemeName,
  ThemeParams,
  ThemeParamsMap,
  ThemeTraits,
} from 'avatarka';
